name: Coverage

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  coverage:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Install Nix
      uses: nixbuild/nix-quick-install-action@v29

    - name: Setup Personal Cachix
      uses: cachix/cachix-action@v14
      with:
        name: nclack
        authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
    
    - name: Setup Nix Community Cachix
      uses: cachix/cachix-action@v14
      with:
        name: nix-community
       
    - name: Setup Magic Nix Cache
      uses: DeterminateSystems/magic-nix-cache-action@main

    - name: Generate coverage reports
      run: nix build .#coverage
        
    - name: Upload to Codecov
      uses: codecov/codecov-action@v5
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        files: result/codecov.json
        fail_ci_if_error: true
        

  # deploy:
  #   needs: coverage
  #   permissions:
  #     pages: write
  #     id-token: write
  #   environment:
  #     name: github-pages
  #     url: ${{ steps.deployment.outputs.page_url }}
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Deploy to GitHub Pages
  #       id: deployment
  #       uses: actions/deploy-pages@v3
