name: Coverage

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  coverage:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Install Nix
      uses: DeterminateSystems/nix-installer-action@main
    
    - name: Setup Nix cache
      uses: DeterminateSystems/magic-nix-cache-action@main
      
    - name: Generate coverage reports
      run: nix build .#coverage
        
    - name: Upload to Codecov
      uses: codecov/codecov-action@v3
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        files: result/codecov.json
        fail_ci_if_error: true
      
    - name: Upload HTML report
      uses: actions/upload-pages-artifact@v2
      with:
        path: result/html/

# Disabled bc pages are not enabled for this repo
  # deploy:
  #   needs: coverage
  #   permissions:
  #     pages: write
  #     id-token: write
  #   environment:
  #     name: github-pages
  #     url: ${{ steps.deployment.outputs.page_url }}
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Deploy to GitHub Pages
  #       id: deployment
  #       uses: actions/deploy-pages@v3
