name: Tests

on:
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  cargo-test:
    strategy:
      matrix:
        os: [macos-latest] #, windows-latest] # disable windows till I figure out the watch tests
    runs-on: ${{ matrix.os }}
    timeout-minutes: 10
    
    steps:
    - uses: actions/checkout@v4
    - uses: dtolnay/rust-toolchain@stable
    - run: cargo test
      
  nix-test:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
    - uses: actions/checkout@v4
    
    - name: Install Nix
      uses: DeterminateSystems/nix-installer-action@main
    
    - name: Setup Nix cache
      uses: DeterminateSystems/magic-nix-cache-action@main
      
    - name: Run checks
      run: nix flake check
      
    - name: Build coverage
      run: nix build .#coverage
      
    - name: Add coverage PR annotations
      run: |
        cat result/coverage-summary.txt >> $GITHUB_STEP_SUMMARY
      
    - name: Upload to Codecov
      uses: codecov/codecov-action@v5
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        files: result/codecov.json
        fail_ci_if_error: true
        flags: unittests
        name: codecov-pr
        verbose: true
