name: Tests

on:
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  cargo-test:
    strategy:
      matrix:
        os: [macos-latest] #, windows-latest] # disable windows till I figure out the watch tests
    runs-on: ${{ matrix.os }}
    timeout-minutes: 10
    
    steps:
    - uses: actions/checkout@v4
    - uses: dtolnay/rust-toolchain@stable
    - run: cargo test
      
  nix-test:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
    - uses: actions/checkout@v4
    
    - name: Install Nix
      uses: nixbuild/nix-quick-install-action@v29

    - name: Setup Personal Cachix
      uses: cachix/cachix-action@v14
      with:
        name: nclack
        authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
    
    - name: Setup Nix Community Cachix
      uses: cachix/cachix-action@v14
      with:
        name: nix-community

    - name: Setup Magic Nix Cache
      uses: DeterminateSystems/magic-nix-cache-action@main
    
    - name: Check final substituters
      run: nix show-config | grep substituters
      
    - name: Run checks
      run: nix flake check
      
    - name: Build coverage
      run: nix build .#coverage
     
    - name: Upload to Codecov
      uses: codecov/codecov-action@v5
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        files: result/codecov.json
        fail_ci_if_error: true
        flags: unittests
        name: codecov-pr
        verbose: true
