name: Tests

on:
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  cargo-test:
    strategy:
      matrix:
        os: [macos-latest] #, windows-latest] # disable windows till I figure out the watch tests
    runs-on: ${{ matrix.os }}
    timeout-minutes: 10
    
    steps:
    - uses: actions/checkout@v4
    - uses: dtolnay/rust-toolchain@stable
    - run: cargo test
      
  nix-test:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
    - uses: actions/checkout@v4
    
    - name: Install Nix
      uses: nixbuild/nix-quick-install-action@v29
    
    - name: Setup Nix cache
      uses: DeterminateSystems/magic-nix-cache-action@main

    - name: Setup Cachix
      uses: cachix/cachix-action@v14
      with:
        name: nix-community
        authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
        extraPullNames: 'nix-community'
        extra_nix_config: |
          extra-substituters = https://cache.nixos.org https://nix-community.cachix.org https://cache.garnix.io
          extra-trusted-public-keys = cache.nixos.org-1:6NCHdD59X431o0gWypbMrAURkbJ16ZPMQFGspcDShjY= nix-community.cachix.org-1:mB9FSh9qf2dCimDSUo8Zy7bkq5CX+/rkCWyvRCYg3Fs= cache.garnix.io:CTFPyKSLcx5RMJKfLo5EEPUObbA78b0YQ2DTCJXqr9g=
      
    - name: Run checks
      run: nix flake check
      
    - name: Build coverage
      run: nix build .#coverage
     
    - name: Upload to Codecov
      uses: codecov/codecov-action@v5
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        files: result/codecov.json
        fail_ci_if_error: true
        flags: unittests
        name: codecov-pr
        verbose: true
